services:
  - type: web
    name: smartanom-backend
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: cd smartanom && python -m gunicorn SmarTanom.wsgi:application
    envVars:
      - key: DATABASE_URL
        value: postgresql://smartanom_user:lAG6IOfYAzXqC8CuT69fjqzV8MAfc7RC@dpg-d0ihg0je5dus739kolc0-a.oregon-postgres.render.com/smartanom
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "false"
      - key: ALLOWED_HOSTS
        value: ".onrender.com"
      - key: PYTHONPATH
        value: "/opt/render/project/src/smartanom"
